fix build for LLVM@18 with LLVM libc++ (macos)
std:fill requires <algorithm>, otherwise it fails:

sergey@Sergeys-MacBook-Air build % make
[  0%] Building CXX object genesis/CMakeFiles/genesis_core.dir/rom.cpp.o
[  0%] Building CXX object genesis/CMakeFiles/genesis_core.dir/smd/smd.cpp.o
In file included from /Users/sergey/atsc/genesis/genesis/smd/smd.cpp:1:
In file included from /Users/sergey/atsc/genesis/genesis/smd/smd.h:5:
In file included from /Users/sergey/atsc/genesis/genesis/m68k/cpu.h:4:
/Users/sergey/atsc/genesis/genesis/m68k/cpu_bus.hpp:52:8: error: no member named 'fill' in namespace 'std'
   52 |                 std::fill(std::begin(bus_state), std::end(bus_state), false);
      |                 ~~~~~^
1 error generated.

Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>